import Head from "next/head";
import Image from "next/image";
import Tabs from "./components/Tabs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nordwest Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width; initial-scale=1; viewport-fit=cover"
        />

        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />

        {/* <!-- possible content values: default, black or black-translucent --> */}
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Tabs></Tabs>
      </main>
    </>
  );
}
