import Head from 'next/head'
import Image from 'next/image'
import Tabs from './components/Tabs';
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
   
    <>
      <Head>
        <title>Nordwest Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Tabs></Tabs>
        
        <h1 className="text-3xl font-bold underline text-blue-100">
          Hello world!
        </h1>
        {/* <Image src="/img/girl.png" alt="girl" width="10vw" height="10vh" layout="responsive" /> */}
        {/* <Image src="/img/girl.png" alt="girl" width="100%" height="100%" layout="responsive" /> */}
      </main>


    </>
   
  )
}
